### ISSUE TITLE
Run away trade placing

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#122]
In the early hours of Oct 10th, the Ireland PPE monitor placed over 1000 trades in a short period of time, rather than the 2 trades / minute that is was suppost to place.

<img src="https://dl.dropbox.com/u/33609233/AppMetrics/2012-09-PPE-CountOfTradesPlaced.png" />

Why?

At the same time, the ListOpenPositions service was slow:

<img src="https://dl.dropbox.com/u/33609233/AppMetrics/2012-09-PPE-Latency-trade-vs-listopenpositions.png" />

**Comment by fandrei** [comment]
Re: [AppMetrics] Run away trade placing (#122)
Hello David,
This was a method that tries to close all currently open positions. Log shows it made a lot of attempts to execute Trade (this must be due to big count of open positions), 
all resulting with error message: Red Card: Price tolerance exceeded
Best wishes,
 Andrei Faber
Wednesday, October 10, 2012, 11:42:43 PM, you wrote:
In the early hours of Oct 10th, the Ireland PPE monitor placed over 1000 trades in a short period of time, rather than the 2 trades / minute that is was suppost to place.
Why?—

**Comment by mrdavidlaing** [comment]
Looks like its happening in PROD too:

<img src="https://dl.dropbox.com/u/33609233/AppMetrics/2012-09-PROD-TradesPlaced.png" />

Kinda violates our "2 trades / min" self throttling :)

Can we:
1.  Prevent the Red Card
2.  Close all the open positions in one request

**Comment by fandrei** [comment]
I have no idea how to avoid this particular error. I'm requesting price and making new trade immediately. Must be something on the server side.

Closing all positions in one request is a good idea. Multiple open positions still will remain open, but at least it won't make series of unsuccessful attempts to close positions. 
Working on this.

**Comment by fandrei** [comment]
Closing all positions in one request - done.
