### ISSUE TITLE
Should we keep OData export service?

### ISSUE THREAD

**Issue by fandrei** [fandrei/AppMetrics#68]
It was used to import data into PowerPivot but didn't show itself as very useful, because it can work only with small amounts of data.

**Comment by mrdavidlaing** [comment]
In the interests of simplicity, lets remove it.

Excel seems pretty good at importing the default tabbed delimited format we
expose for Solarwinds, so that will do instead of OData

On 1 May 2012 09:35, fandrei <
reply@reply.github.com

> wrote:
> 
> It was used to import data into PowerPivot but didn't show itself as very
> useful, because it can work only with small amounts of data.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/68

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
UPD Currently it's used by integration tests; if we need to remove OData service, it's necessary to create a replacement raw data access interface.

**Comment by mrdavidlaing** [comment]
Your call

On 7 May 2012 04:59, fandrei <
reply@reply.github.com

> wrote:
> 
> UPD Currently it's used by integration tests; if we need to remove OData
> service, it's necessary to create a replacement data access method.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/68#issuecomment-5543586

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing
